<?php

/**
 * Implements hook_theme().
 */
function itunes_rss_theme() {
  $theme_registry['views_view_itunes_rss'] = [
    'variables' => [
        'view' => NULL,
        'options' => NULL,
        'rows' => NULL,
        'title' => NULL,
      ],
    'path' => 'templates',
    'includes' => ['core/modules/views/views.theme.inc'],
    'template' => 'views-view-itunes-rss',
  ];
  return $theme_registry;
}

/**
 * Prepares variables for RSS feed templates.
 *
 * Default template: views-view-rss.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The raw row data.
 */
function template_preprocess_views_view_itunes_rss(&$variables) {
  template_preprocess_views_view_rss($variables);

  $view  = $variables['view'];
  $items = $variables['rows'];
  $style = $view->style_plugin;
  $variables['image_url'] = $style->getImage();
  $variables['itunes_category'] = $style->options['category'];
  $variables['itunes_explicit'] = $style->options['explicit'] ? 'yes' : 'no';
  $variables['itunes_name'] = $style->options['name'];
  $variables['itunes_email'] = $style->options['email'];
}
